class AddPartidos < ActiveRecord::Migration[5.2]
  def up
    Partido.create(equipo1: "Rusia", equipo2: "Arabia Saudita", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Egipto", equipo2: "Uruguay", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Rusia", equipo2: "Egipto", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Uruguay", equipo2: "Arabia Saudita", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Uruguay", equipo2: "Rusia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Arabia Saudita", equipo2: "Egipto", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Marruecos", equipo2: "Irán", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Portugal", equipo2: "España", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Portugal", equipo2: "Marruecos", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Irán", equipo2: "España", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "España", equipo2: "Marruecos", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Irán", equipo2: "Portugal", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Francia", equipo2: "Australia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Perú", equipo2: "Dinamarca", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Francia", equipo2: "Perú", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Dinamarca", equipo2: "Australia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Dinamarca", equipo2: "Francia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Australia", equipo2: "Perú", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Argentina", equipo2: "Islandia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Croacia", equipo2: "Nigeria", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Argentina", equipo2: "Croacia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Nigeria", equipo2: "Islandia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Islandia", equipo2: "Croacia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Nigeria", equipo2: "Argentina", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Costa Rica", equipo2: "Serbia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Brasil", equipo2: "Suiza", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Brasil", equipo2: "Costa Rica", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Serbia", equipo2: "Suiza", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Serbia", equipo2: "Brasil", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Suiza", equipo2: "Costa Rica", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Alemania", equipo2: "México", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Suecia", equipo2: "Corea del Sur", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Alemania", equipo2: "Suecia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Corea del Sur", equipo2: "México", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "México", equipo2: "Suecia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Corea del Sur", equipo2: "Alemania", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Bélgica", equipo2: "Panamá", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Túnez", equipo2: "Inglaterra", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Bélgica", equipo2: "Túnez", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Inglaterra", equipo2: "Panamá", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Inglaterra", equipo2: "Bélgica", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Panamá", equipo2: "Túnez", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Polonia", equipo2: "Senegal", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Colombia", equipo2: "Japón", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Japón", equipo2: "Senegal", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Polonia", equipo2: "Colombia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Senegal", equipo2: "Colombia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)
    Partido.create(equipo1: "Japón", equipo2: "Polonia", resultado: 0, golesEquipo1: 0, golesEquipo2: 0, fecha: 0, lugar: 0)

  end
end
