class AddEquipos < ActiveRecord::Migration[5.2]
  def up
    Equipo.create(codigo: "RUS", nombre: "Rusia", idGrupo: 1, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "KSA", nombre: "Saudi Arabia", idGrupo: 1, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "EGY", nombre: "Egipto", idGrupo: 1, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "URU", nombre: "Uruguay", idGrupo: 1, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "POR", nombre: "Portugal", idGrupo: 2, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "ESP", nombre: "España", idGrupo: 2, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "MAR", nombre: "Marruecos", idGrupo: 2, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "IRN", nombre: "Irán", idGrupo: 2, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "FRA", nombre: "Francia", idGrupo: 3, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "AUS", nombre: "Australia", idGrupo: 3, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "PER", nombre: "Perú", idGrupo: 3, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "DEN", nombre: "Dinamarca", idGrupo: 3, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "ARG", nombre: "Argentina", idGrupo: 4, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "ISL", nombre: "Islandia", idGrupo: 4, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "CRO", nombre: "Croacia", idGrupo: 4, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "NGA", nombre: "Nigeria", idGrupo: 4, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "BRA", nombre: "Brasil", idGrupo: 5, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "SUI", nombre: "Suiza", idGrupo: 5, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "CRC", nombre: "Costa Rica", idGrupo: 5, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "SRB", nombre: "Serbia", idGrupo: 5, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "GER", nombre: "Alemania", idGrupo: 6, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "MEX", nombre: "México", idGrupo: 6, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "SWE", nombre: "Suecia", idGrupo: 6, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "KOR", nombre: "Corea del Sur", idGrupo: 6, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "BEL", nombre: "Bélgica", idGrupo: 7, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "PAN", nombre: "Panamá", idGrupo: 7, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "TUN", nombre: "Túnez", idGrupo: 7, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "ENG", nombre: "Inglaterra", idGrupo: 7, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "POL", nombre: "Polonia", idGrupo: 8, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "SEN", nombre: "Senegal", idGrupo: 8, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "COL", nombre: "Colombia", idGrupo: 8, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)
    Equipo.create(codigo: "JPN", nombre: "Japón", idGrupo: 8, puntos: 0, partidosJugados: 0, partidosGanados: 0, partidosEmpatados: 0, partidosPerdidos: 0, golesFavor: 0, golesContra: 0)

  end
end
